# Generated by Django 5.2.8 on 2025-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notPayed', 'NotPayed'), ('payed', 'Payed')], default='notPayed', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('paidAmount', models.FloatField(default=0)),
                ('paymentMethod', models.CharField(max_length=20)),
                ('cashier', models.CharField(max_length=200)),
                ('IVA', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
        ),
    ]
