# Generated by Django 5.2.7 on 2025-11-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notPayed', 'NotPayed'), ('payed', 'Payed')], default='notPayed', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
