# Generated by Django 5.2.7 on 2025-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_iva_bill_amount_bill_discount_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
