# Generated by Django 5.2.7 on 2025-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'disponible'), ('occupied', 'ocupada'), ('reserved', 'reservada'), ('in_cleaning', 'en limpieza')], default='available', max_length=20)),
            ],
        ),
    ]
