# Generated by Django 5.2.7 on 2025-11-04 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notPayed', 'NotPayed'), ('payed', 'Payed')], default='notPayed', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('in_cleaning', 'In Cleaning')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('notCooking', 'notCooking'), ('cooking', 'Cooking'), ('ready', 'Ready')], default='notCooking', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.bill')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
            ],
        ),
    ]
