# Generated by Django 5.2.7 on 2025-10-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
                ('createdAt', models.CharField()),
                ('closedAt', models.CharField()),
            ],
        ),
    ]
