# Generated by Django 5.2.7 on 2025-10-29 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notcooking', 'notCooking'), ('cooking', 'Cooking'), ('ready', 'Ready')], default='notCooking', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='closedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('notPayed', 'NotPayed'), ('payed', 'Payed')], default='notPayed', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('in_cleaning', 'In Cleaning')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='tables.bill')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.product')),
            ],
        ),
    ]
