# Generated by Django 5.2.7 on 2025-11-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_remove_bill_table_order_bill_order_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('notCooking', 'notCooking'), ('cooking', 'Cooking'), ('ready', 'Ready')], default='notCooking', max_length=20),
        ),
    ]
