# Generated by Django 5.2.8 on 2025-11-20 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_5_cordobas', models.IntegerField(default=0)),
                ('bill_10_cordobas', models.IntegerField(default=0)),
                ('bill_20_cordobas', models.IntegerField(default=0)),
                ('bill_50_cordobas', models.IntegerField(default=0)),
                ('bill_100_cordobas', models.IntegerField(default=0)),
                ('bill_200_cordobas', models.IntegerField(default=0)),
                ('bill_500_cordobas', models.IntegerField(default=0)),
                ('bill_1000_cordobas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='close', max_length=200)),
                ('cashierId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_inflow', models.FloatField(null=True)),
                ('cash_outflow', models.FloatField(null=True)),
                ('amount', models.FloatField()),
                ('method', models.CharField()),
                ('description', models.TextField(default='bill payment')),
                ('created_at', models.DateField()),
                ('denominations', models.JSONField(default=dict)),
                ('cashierId', models.CharField(max_length=200)),
                ('cashRegisterNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashRegister.cashregister')),
            ],
        ),
    ]
